
defaults:
  - model: L2_H2_E64.yaml

dataset:
  train_length: 15
  max_data_num: 100000
  noise_ratio: [0.0, 0.0]
  # skip_train_noisy:
  # skip_train_special_code: 
  # only_train_noisy:
  # only_train_special_code: 
  general: [True, True]
  only_special_code: [False, True]
  only_noise: [False, False]
  noisy_special_code: [False, False]

optimizer:
  optimizer_name: AdamW
  learning_rate: 1e-4
  weight_decay: 1
  momentum: 

train:
  exp_name: wd1_pure-mixed
  seed: 42
  wandb: True
  wandb_project_name: confounder_analysis
  wandb_entity: lklab_kaist
  batch_size: 128
  warmup_steps: 0
  config_steps: [2000, 300]
  max_grad_norm: 
  val_interval: 4
  save_model_interval: 